branch-defaults:
  feature/database-setup_elastic-beanstalk:
    environment: NeighborhoodChefBE-prod
  feature/https-instance_config:
    environment: NeighborhoodChefBE-prod
  feature/database-setup-remix:
    environment: NeighborhoodChefBE-prod
  master:
    environment: NeighborhoodChefBE-prod
environment-defaults:
  NeighborhoodChefBE-prod:
    branch: null
    repository: null
global:
  application_name: NeighborhoodChefBE
  default_ec2_keyname: aws-eb
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
